---
- name: install nfs server
  hosts: nfs_server
  remote_user: root
  tasks:
  - name: install nfs server
    shell:
      cmd: |
        apt-get update -y
        apt-get update -y && apt install -y nfs-kernel-server
        cat >> /etc/exports<<EOF
        /mnt/md0  *(rw,async,no_subtree_check,no_root_squash)
        EOF
        systemctl enable nfs-server.service
        systemctl start nfs-server.service
        systemctl status nfs-server.service
        ufw disable
